#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# NIZAM-RUS — Production Deployment Script
# ─────────────────────────────────────────────────────────────────────────────
#
# USAGE (run as root or with sudo on a fresh Ubuntu 22.04 VPS):
#   chmod +x deploy.sh
#   sudo ./deploy.sh
#
# WHAT IT DOES:
#   1. Installs system dependencies (Python 3.11, Nginx, Certbot)
#   2. Creates a non-root user 'nizamuser' to run the app
#   3. Clones/copies the project to /var/www/nizam-rus-backend
#   4. Sets up the Python virtualenv and installs pip packages
#   5. Creates the .env file (prompts you for values)
#   6. Runs Alembic migrations to create the database
#   7. Copies Nginx and systemd configs and enables them
#   8. Obtains a TLS certificate via Let's Encrypt (optional)
# ─────────────────────────────────────────────────────────────────────────────

set -e   # Exit immediately if any command fails
set -u   # Treat unset variables as errors

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── Config — edit these before running ────────────────────────────────────────
APP_DIR="/var/www/nizam-rus-backend"
FRONTEND_DIR="/var/www/nizam-rus"
APP_USER="nizamuser"
DOMAIN=""                    # e.g. "nizam-rus.com" — leave empty to skip SSL

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1 — System dependencies
# ─────────────────────────────────────────────────────────────────────────────
info "Installing system packages..."
apt update -qq
apt install -y python3.11 python3.11-venv python3-pip nginx certbot python3-certbot-nginx curl

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2 — App user
# ─────────────────────────────────────────────────────────────────────────────
if ! id "$APP_USER" &>/dev/null; then
    info "Creating user $APP_USER..."
    useradd --system --shell /bin/bash --create-home "$APP_USER"
fi

# ─────────────────────────────────────────────────────────────────────────────
# STEP 3 — Copy project files
# ─────────────────────────────────────────────────────────────────────────────
info "Setting up project directory at $APP_DIR..."
mkdir -p "$APP_DIR"
# If running from the project directory:
cp -r . "$APP_DIR/"
# OR clone from git:
# git clone https://github.com/youruser/nizam-rus-backend.git "$APP_DIR"

chown -R "$APP_USER":"$APP_USER" "$APP_DIR"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 4 — Python virtualenv
# ─────────────────────────────────────────────────────────────────────────────
info "Creating Python virtual environment..."
sudo -u "$APP_USER" python3.11 -m venv "$APP_DIR/venv"
sudo -u "$APP_USER" "$APP_DIR/venv/bin/pip" install --quiet --upgrade pip
sudo -u "$APP_USER" "$APP_DIR/venv/bin/pip" install --quiet -r "$APP_DIR/requirements.txt"
sudo -u "$APP_USER" "$APP_DIR/venv/bin/pip" install --quiet gunicorn

info "Dependencies installed."

# ─────────────────────────────────────────────────────────────────────────────
# STEP 5 — .env configuration
# ─────────────────────────────────────────────────────────────────────────────
if [ ! -f "$APP_DIR/.env" ]; then
    info "Configuring environment..."

    # Generate a random JWT secret key
    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " Please provide the following configuration values:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    read -rp "Your domain (e.g. nizam-rus.com): " INPUT_DOMAIN
    DOMAIN="${INPUT_DOMAIN:-localhost}"

    read -rp "Resend API key (leave blank to use SMTP): " RESEND_KEY
    read -rp "Email FROM address (e.g. noreply@nizam-rus.com): " EMAIL_FROM

    if [ -z "$RESEND_KEY" ]; then
        read -rp "SMTP host (e.g. smtp.gmail.com): " SMTP_HOST
        read -rp "SMTP user (your email): " SMTP_USER
        read -rsp "SMTP password (app password): " SMTP_PASS
        echo ""
    fi

    cat > "$APP_DIR/.env" << EOF
# Generated by deploy.sh on $(date)
APP_NAME=NIZAM-RUS
APP_ENV=production
FRONTEND_ORIGIN=https://${DOMAIN}

DATABASE_URL=sqlite+aiosqlite:///./nizam_rus.db

JWT_SECRET_KEY=${JWT_SECRET}
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
JWT_REFRESH_TOKEN_EXPIRE_DAYS=30

VERIFICATION_TOKEN_EXPIRE_HOURS=24

RESEND_API_KEY=${RESEND_KEY:-}
EMAIL_FROM=${EMAIL_FROM:-noreply@${DOMAIN}}
EMAIL_FROM_NAME=NIZAM-RUS

SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
SMTP_PORT=587
SMTP_USER=${SMTP_USER:-}
SMTP_PASSWORD=${SMTP_PASS:-}
SMTP_TLS=true
EOF

    chmod 600 "$APP_DIR/.env"    # Only the owner can read — hides the JWT secret
    chown "$APP_USER":"$APP_USER" "$APP_DIR/.env"
    info ".env created with a random JWT secret."
else
    warn ".env already exists — skipping configuration step."
fi

# ─────────────────────────────────────────────────────────────────────────────
# STEP 6 — Database migrations
# ─────────────────────────────────────────────────────────────────────────────
info "Running Alembic migrations..."
cd "$APP_DIR"
sudo -u "$APP_USER" "$APP_DIR/venv/bin/alembic" upgrade head
info "Database schema is up to date."

# ─────────────────────────────────────────────────────────────────────────────
# STEP 7 — Systemd service
# ─────────────────────────────────────────────────────────────────────────────
info "Installing systemd service..."
sed "s|/var/www/nizam-rus-backend|$APP_DIR|g" \
    "$APP_DIR/deploy/nizam-rus.service" \
    | sed "s|User=www-data|User=$APP_USER|g" \
    | sed "s|Group=www-data|Group=$APP_USER|g" \
    > /etc/systemd/system/nizam-rus.service

systemctl daemon-reload
systemctl enable nizam-rus
systemctl start nizam-rus

if systemctl is-active --quiet nizam-rus; then
    info "✅ nizam-rus service is running."
else
    error "Service failed to start. Check logs: journalctl -u nizam-rus -n 50"
fi

# ─────────────────────────────────────────────────────────────────────────────
# STEP 8 — Nginx
# ─────────────────────────────────────────────────────────────────────────────
info "Configuring Nginx..."

# Copy frontend HTML (assumes it's in a 'frontend' subdirectory of the project)
mkdir -p "$FRONTEND_DIR"
if [ -f "$APP_DIR/frontend/NIZAM-RUS.html" ]; then
    cp "$APP_DIR/frontend/NIZAM-RUS.html" "$FRONTEND_DIR/index.html"
    chown -R www-data:www-data "$FRONTEND_DIR"
    info "Frontend HTML copied to $FRONTEND_DIR"
fi

# Set up Nginx config
sed "s|yourdomain.com|$DOMAIN|g" \
    "$APP_DIR/deploy/nginx.conf" \
    | sed "s|/var/www/nizam-rus|$FRONTEND_DIR|g" \
    > /etc/nginx/sites-available/nizam-rus

ln -sf /etc/nginx/sites-available/nizam-rus /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

nginx -t && systemctl reload nginx
info "✅ Nginx configured."

# ─────────────────────────────────────────────────────────────────────────────
# STEP 9 — TLS certificate (optional, requires a real domain)
# ─────────────────────────────────────────────────────────────────────────────
if [ -n "$DOMAIN" ] && [ "$DOMAIN" != "localhost" ]; then
    info "Obtaining TLS certificate for $DOMAIN..."
    certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "admin@$DOMAIN" || \
        warn "Certbot failed — run manually: sudo certbot --nginx -d $DOMAIN"
fi

# ─────────────────────────────────────────────────────────────────────────────
# DONE
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN} NIZAM-RUS Deployment Complete!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " API:      http://${DOMAIN}/api/"
echo " Docs:     (disabled in production — set APP_ENV=development to enable)"
echo " Logs:     sudo journalctl -u nizam-rus -f"
echo " Restart:  sudo systemctl restart nizam-rus"
echo " Status:   sudo systemctl status nizam-rus"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
